### ISSUE TITLE
BUG ShopifyImportTask - newly imported products are published, but $owns (images) are not

### ISSUE THREAD

**Issue by jsirish** [dynamic/silverstripe-shopify#78] opened 2021-05-03 23:17 UTC
Ideally, a new product would not be published on import so things like blocks can be added prior to publishing.

Currently, a newly imported product is published, but the related records such as Images are not. Currently requires a manual publish for the images to show on FE

**Comment by mak001** [comment] 2021-07-19 15:23
I think its caused by https://github.com/dynamic/silverstripe-shopify/blob/5c5da4ef62574025d5b2d8113b36c1dc4bfab9dc/src/Task/ShopifyImportTask.php#L247

The isLiveVersion() call doesn't seem to take into account the related objects as seen in https://github.com/silverstripe/silverstripe-versioned/blob/32b7282cbf5100dc56919698c5cef28c0204fd33/src/Versioned.php#L2792-L2801

removing the isLiveVersion check will fix it, but may come at a slight performance hit

**Comment by mak001** [comment] 2021-10-01 15:57
Should be fixed in #116 which removes versioning from shopify files. They don't have versions in the graphql api.

**Closed by mak001** 2021-10-01 15:57 UTC
Labels: affects/v1.0, backend
